### ISSUE TITLE
[Page: Mentoring/Discussion] [C#] Unable to start discussion Error

### ISSUE THREAD

**Issue by wischi-chr** [exercism/v3-beta#126]
I just tried to mentor a pretty old request (about 2 years) and got a "Unable to start discussion" error:
![image](https://user-images.githubusercontent.com/2495113/126017877-348fc862-4f77-4c15-891b-c5b2a7e8f5e5.png)
`Mentoring Request: https://exercism.lol/mentoring/requests/7b9039a8-a831-11eb-b069-cd08bd9fe49b`

The request to the backend that fails:
![image](https://user-images.githubusercontent.com/2495113/126017975-1632c261-aca3-46d0-a92f-ed7f1db52c3a.png)

**Comment by wischi-chr** [comment]
Maybe related to #110 ?

**Comment by iHiD** [comment]
@kntsoriano Can you take a look at this pls.

**Comment by kntsoriano** [comment]
@iHiD I think this bug occurs because the request attached to it has a blank `comment_markdown` field. When we update the request's status to fulfilled, we re run validations and this error occurs. I think what we should do is to either disable validations for old requests, or add a stub `content_markdown` field for those.

**Comment by kntsoriano** [comment]
@iHiD When this is fixed, we can also close https://github.com/exercism/website/issues/1206.
