### ISSUE TITLE
Shows wrong info under task for a exercise

### ISSUE THREAD

**Issue by 18-F-cali** [exercism/v3-beta#228]
I am solving Interesting is interesting on the c# track
here: https://exercism.lol/tracks/csharp/exercises/interest-is-interesting/edit
Expectation: Under the task 3 it should have info regarding the task like 
![image](https://user-images.githubusercontent.com/63421973/130450901-a638425f-8822-4fb7-a01f-bab1662cfbdf.png)
 but is showing 
![image](https://user-images.githubusercontent.com/63421973/130451014-31b1e094-1e7e-4e6e-8524-366cdcf691b4.png)
 where it is showing the solution itself.
Here the expected learning are
1. floating point numbers
2. while loops
3. do while loops

**Comment by angelikatyborska** [comment]
@18-F-cali on your screenshot, task 3 is not expanded. You need to expand it to see its content.

@iHiD I think the design calls for much more visual separation between task 3 and how to debug, like a big margin and definitely a final bottom border. I keep not noticing that the last task is there all the time...

As for the "example file", it's there for debugging purposes so that you can quickly copy-paste a correct solution if you need to and will be deleted before the launch.

**Comment by 18-F-cali** [comment]
@angelikatyborska Yup, you are right. i apologize for creating a issue.

**Comment by 18-F-cali** [comment]
@angelikatyborska  Should i close this issue?

**Comment by angelikatyborska** [comment]
Let's keep it open to see what @iHiD thinks about a design change here. It's not entirely your fault that you didn't notice that the last step still needed to be expanded.

**Comment by taiyab** [comment]
Taking a look.
