### ISSUE TITLE
Fix test runners

### ISSUE THREAD

**Issue by iHiD** [exercism/v3-beta#306]
According to the ever reliable @angelikatyborska, these are all broken. Individual issues in the **slack** channels:

```
clojurescript
cpp
emacs-lisp
groovy
kotlin
lfe
mips
objective c
ocaml
scala
scheme
swift
tcl
```

Also we need to ensure these are disabled:
```
delphi
pharo
pl/sql
z3
```

**Comment by junedev** [comment]
For reference: https://exercism-team.slack.com/archives/CR91YFNG3/p1630081000028300?thread_ts=1630081000.028300&cid=CR91YFNG3

**Comment by iHiD** [comment]
Update. @angelikatyborska has fixed lots 🙂 There was an issue with `output` vs `message` keys. I've left those for you to check/merge/test, @ErikSchierboom, and there might be some that need your input still 🙂

**Comment by angelikatyborska** [comment]
> Also we need to ensure these are disabled:

I checked and all of the test runners that weren't implemented yet have `status.test_runner` in `config.json` set to `false` so I guess it's just about respecting those settings.

**Comment by iHiD** [comment]
Great. Thanks. We respect that as yesterday (or at least the PR went in - can't remember if it got merged yet)

**Comment by ErikSchierboom** [comment]
> I checked and all of the test runners that weren't implemented yet have status.test_runner in config.json set to false so I guess it's just about respecting those settings.

Yeah, I ran a script a couple of weeks back to check that.

>  @angelikatyborska has fixed lots 🙂

Sweet. I've merged all of them. @angelikatyborska could you re-run your script to verify that they fixed test runners are now working as expected?

**Comment by angelikatyborska** [comment]
> I'm assuming you have a script

No, I was checking everything manually via exercism.lol

After rechecking again:

- clojurescript crashed on the first ran, then worked correctly every next run
- cpp works
- emacs-list works
- mips works
- groovy works
- ocaml works
- tcl works

LFE wasn't merged yet https://github.com/exercism/lfe-test-runner/pull/21 I did reset my progress on the track to force my exercises to be brand new, that did solve my problem with hello-world passing when very very wrong solutions are given.

**Comment by ErikSchierboom** [comment]
Thanks for checking. I just merged LFE

**Comment by ErikSchierboom** [comment]
Okay, the failing test runners are then:

- kotlin: this is a [known issue](https://github.com/exercism/kotlin-test-runner/issues/16) with not being able to run without networking. The `.status.test_runner` and `.status.concept_exercises` fields are set to `false` and no so no immediate issue here.
- objective c: this test runner has not been implemented. The `.status.test_runner` field is set to `false` so no immediate issue here.
- scala: this was functionally working some time ago, but with the caveat that it always times out. I've not yet found a way to speed it up. The `.status.test_runner` and `.status.concept_exercises` fields are set to `false` and no so no immediate issue here.
- scheme: worked me for when I reset the track. @angelikatyborska is it still failing for you?
- swift: this has never really worked, as I can't even get the Dockerfile built due to a Swift compile error that I don't know how to fix. Swift does have `.status.concept_exercises` enabled. @iHiD We probably want to disable Swift due to the test runner not working?

**Comment by angelikatyborska** [comment]
@ErikSchierboom Scheme technically works, but it "doesn't work" in the sense that it doesn't tell you why a test is failing. There's no message, no test code, only the test name.

![Screen Shot 2021-08-30 at 11 39 54](https://user-images.githubusercontent.com/7852553/131320122-5673be20-3dd4-4fc1-892d-1aac2c9a9b10.png)

**Comment by ErikSchierboom** [comment]
@angelikatyborska Ah, right. I'll check

**Comment by iHiD** [comment]
>  Swift does have .status.concept_exercises enabled. @iHiD We probably want to disable Swift due to the test runner not working?

I'm ok with leaving it on the site I think.

**Comment by ErikSchierboom** [comment]
Okay!

**Comment by ErikSchierboom** [comment]
I've created an [issue](https://github.com/exercism/scheme-test-runner/issues/17) for the Scheme test runner. The rest is either working or disabled, so I think we can close this.
